version: '3.10'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    command: >
      /bin/sh -c "
      alembic upgrade head &&
      flake8 . &&
      uvicorn settings.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - ./backend/.env
    depends_on:
      - database
    extra_hosts:
      - "opti.local.com:host-gateway"

  database:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=blog_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "54322:5432"

volumes:
    postgres_data:
