"""Added account table

Revision ID: 2834c0078f7e
Revises: 3c064a4ebc4f
Create Date: 2024-11-14 11:37:00.772291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2834c0078f7e'
down_revision: Union[str, None] = '3c064a4ebc4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('updated_file', sa.String(), nullable=True))
    op.drop_column('articles', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('articles', 'updated_file')
    # ### end Alembic commands ###
