"""Added nulltable

Revision ID: 3c064a4ebc4f
Revises: 60de3931cd69
Create Date: 2024-11-14 11:33:22.399299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c064a4ebc4f'
down_revision: Union[str, None] = '60de3931cd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'file',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'file',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
