"""Information about original file

Revision ID: 60de3931cd69
Revises: 510e09192727
Create Date: 2024-11-14 11:30:44.227892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60de3931cd69'
down_revision: Union[str, None] = '510e09192727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('original_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'original_file')
    # ### end Alembic commands ###
