"""Added account table

Revision ID: cbb2df925030
Revises: 2834c0078f7e
Create Date: 2024-11-14 17:22:09.955925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbb2df925030'
down_revision: Union[str, None] = '2834c0078f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

refactor_type_enum = sa.Enum('APA', 'Custom', name='refactortype')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    refactor_type_enum.create(op.get_bind())
    op.add_column('articles', sa.Column('refactor_type', sa.Enum('APA', 'Custom', name='refactortype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'refactor_type')
    op.drop_column('articles', 'refactor_type')
    # ### end Alembic commands ###
